import { TokenizedAsset } from "@/types";
export const allTokenizedAsset: TokenizedAsset[] = [
  {
    id: "OFF-003",
    assetName: "Audemars Piguet Royal Oak 15400ST",
    brand: "Audemars Piguet",
    model: "Royal Oak 15400ST.OO.1220ST.03",
    year: 2019,
    condition: "Very Good",
    totalUnits: 150,
    pricePerUnit: 383,
    soldUnits: 142,
    availableUnits: 8,
    soldPercentage: 94.7,
    rentalYieldApy: 7.8,
    totalValue: 57450,
    investors: 41,
    status: "active",
    authenticityVerified: true,
    images: ["/api/placeholder/400/300"],
    description: "The Audemars Piguet Royal Oak 15400ST features the classic octagonal bezel and 'Grande Tapisserie' dial in blue. This 41mm stainless steel model is a perfect blend of elegance and sportiness.",
    documents: [
        { title: "Authenticity Certificate", url: "#" }
    ]
  },
  {
    id: "OFF-004",
    assetName: "Omega Speedmaster Moonwatch",
    brand: "Omega",
    model: "Speedmaster Professional Moonwatch",
    year: 2022,
    condition: "New",
    totalUnits: 80,
    pricePerUnit: 75,
    soldUnits: 0,
    availableUnits: 80,
    soldPercentage: 0,
    rentalYieldApy: 9.2,
    totalValue: 6000,
    investors: 0,
    status: "upcoming",
    authenticityVerified: true,
    images: ["/api/placeholder/400/300"],
    description: "The Omega Speedmaster Professional Moonwatch is the only watch to have been worn on the moon. This new model features the Co-Axial Master Chronometer Calibre 3861.",
    documents: []
  },
  {
    id: "OFF-005",
    assetName: "Cartier Santos Large",
    brand: "Cartier",
    model: "Santos de Cartier Large WSSA0029",
    year: 2021,
    condition: "Excellent",
    totalUnits: 120,
    pricePerUnit: 58,
    soldUnits: 120,
    availableUnits: 0,
    soldPercentage: 100,
    rentalYieldApy: 5.5,
    totalValue: 6960,
    investors: 34,
    status: "sold-out",
    authenticityVerified: true,
    images: ["/api/placeholder/400/300"],
    description: "The Santos de Cartier is a modern icon with its exposed screws and ergonomic curved case. This large model comes with a stainless steel bracelet and an interchangeable leather strap.",
    documents: [
        { title: "Authenticity Certificate", url: "#" }
    ]
  },
];
